// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

import { Source_Sans_3, Source_Serif_4 } from "next/font/google";
import "./globals.css";

const body = Source_Sans_3({ subsets: ["latin"], variable: "--font-body" });
const display = Source_Serif_4({ subsets: ["latin"], variable: "--font-display" });

export const metadata = {
  title: "Tavishi Kashyap | Java & Spring Boot Developer",
  description:
    "Computer Science student building backend and full-stack software with Java, Spring Boot, REST APIs, databases, React and machine learning.",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${body.variable} ${display.variable}`}>
      <body>{children}</body>
    </html>
  );
}
